### ISSUE TITLE
Build process fails

### ISSUE THREAD

**Issue by ZeeshanJan** [Blockchain-Technology-Lab/edi-frontend#6]
While it works well on localhost, it produces an error during the build process

`61:5  Error: React Hook "useDoughnutCsvLoader" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function.  react-hooks/rules-of-hooks`

https://github.com/Blockchain-Technology-Lab/edi-frontend/blob/efa08c2130774b341222da2669c4a982975f5795/src/pages/software/doughnut/index.tsx#L61

**Comment by ianhanssoniohk** [comment]
Hi Zeeshan, this is because react hooks (i.e useEffect which is used in that function) have to be called a predictable number of times and order within a given component as they rely on executive order.

This would usually be solved by separating out the individual blocks to handle their own data. I.e:
```
const paths = ...
return (paths.map(path => <Item key={path} path={path} />))

...

function Item({path}){
  const results = useDoughnutCsvLoader(path)
  return <>My component</>
}
```

If you need to get all of the data from the parent and do some transformation to it then the hook would need to be amended (or a second one created) to take in an array of paths and resolve all the promises. If you want us to do that then I can have Leandro look at it.

**Comment by ZeeshanJan** [comment]
Hi Ian,

I have been trying to implement the logic of separating out individual blocks, but I haven't found a solution yet.

Yes, I’d appreciate it if Leandro could take a look at it.

**Comment by ZeeshanJan** [comment]
Hi Ian,

I did the following commit and it seems to be working.

Could you please check if it meets the standards?

the commit: b3e846358b127341172d4145423244dea264c676

**Comment by ianhanssoniohk** [comment]
I don't think it would as functionally it is essentially the same as before although the linter may not catch it. I can have Leandro look at it on Monday.

**Comment by leandroiohk** [comment]
Hi @ZeeshanJan! I just raised a PR addressing this issue. The problem was that useDoughnutCsvLoader, a custom hook, was being called inside a function instead of at the top level of the component. React’s rules of hooks require all hooks to be called unconditionally at the top level to ensure they run consistently on each render. Please let me know if you need anything else 🙂

**Comment by ZeeshanJan** [comment]
Hi @leandroiohk,
Thank you very much for your assistance; I have merged the PR. I truly appreciate your help in developing and maintaining the dashboard.

Thanks @ianhanssoniohk 👍
